### PR TITLE
Add D8 batch runner support

### PR DESCRIPTION
**Pull request by caitp**
I didn't realize before suggesting this to @jugglinmike that the API was already exposed in D8.

### CODE REVIEW

**Comment by caitp** [comment]
WRT asynchronous tests, something like @btford's [zone.js](https://github.com/angular/zone.js) might be suitable (specific to spec'd async stuff, I guess)

**Comment by caitp** [comment]
```
EchoBeach:test262-harness caitp$ ./bin/run.js -r "d8" -e "~/v8/out/x64.release/d8" -b true "../test262/test/built-ins/Array/*.js"
Ran 55 tests
55 passed
0 failed
Took 0.144 seconds

EchoBeach:test262-harness caitp$ ./bin/run.js -r "d8" -e "~/v8/out/x64.release/d8" -b true "../test262/test/built-ins/Function/*.js"
Ran 169 tests
169 passed
0 failed
Took 0.439 seconds
```

It works pretty nicely --- still fails on cases where the helpers aren't available, but hey.

**Comment by bterlson** [comment]
Hey, awesome! Yeah I need to fix the helpers thing... I am hoping to get to that this week!

Know where I can pick up D8 builds? :-P

**Comment by caitp** [comment]
> Know where I can pick up D8 builds? :-P

Maybe @domenic or one of the other chromium folks could arrange to have nightly D8 builds published somewhere

**Pull request merged**
