### PR TITLE
Allow reporters to write to log files as well

### PR DESCRIPTION
**Pull request by avdg**
This pr should allow to store log results to a file, which would be helpful for windows (as there isn't an easy and reliable stdout pipe syntax) or for programs that simply prefer to process files instead of stdout streams.

I'm not really sure how the api should look like and I might need to test this patch a bit more (I might have missed a few edgy cases).

For now I have put the output api inside the resultsEmitter and didn't touch anything related with the readline api.

### CODE REVIEW

**Comment by bterlson** [comment]
Gah, somehow I missed this PR.

Can you explain "no reliable stdout pipe syntax"? `test262-harness > foo.txt` should work fine right?

**Comment by avdg** [comment]
Uh... I'm offline for a big part of my time now so I actually just read that message. Not sure if I have the time to answer in time.

**Comment by avdg** [comment]
Uh I guess atom doesn't like to show these files pretty... It shows 2 special unicode chars followed by the first line. And every line is separated by 2 lines instead of a single line.

**Comment by avdg** [comment]
Well, in sublime it looks way better at least...

**Comment by bterlson** [comment]
Redirection should be working fine now.

**Pull request closed without merging**
