### PR TITLE
First pass at implementation of features filter. Ref gh-84

### PR DESCRIPTION
**Pull request by rwaldron**
@leobalter

### CODE REVIEW

**Comment by mathiasbynens** [comment]
I just needed this today! This would be immensely useful. Thank you for your work on this.

**Comment by mathiasbynens** [comment]
I suppose the flag should be added to https://github.com/bterlson/test262-harness#options as well.

**Comment by rwaldron** [comment]
@mathiasbynens @leobalter I added the option flag to the table, it's also linked to the actual features.txt in Test262. https://github.com/rwaldron/test262-harness/blob/9f37fd939b8ea0a8192828d095759803ea12f540/README.md#options PTAL?

**Comment by leobalter** [comment]
LGTM!

**Comment by rwaldron** [comment]
Thanks

**Pull request merged**
